use XueXiao
create table 中国姓
(
[姓_ID] int  IDENTITY (1, 1) NOT NULL  primary key,
[姓] varchar(4)
)
insert dbo.中国姓(姓)
values('赵')
insert dbo.中国姓(姓)
values('钱')
insert dbo.中国姓(姓)
values('孙')
insert dbo.中国姓(姓)
values('李')
insert dbo.中国姓(姓)
values('周')
insert dbo.中国姓(姓)
values('吴')
insert dbo.中国姓(姓)
values('郑')
insert dbo.中国姓(姓)
values('王')
insert dbo.中国姓(姓)
values('冯')
insert dbo.中国姓(姓)
values('陈')
insert dbo.中国姓(姓)
values('褚')
insert dbo.中国姓(姓)
values('卫')
insert dbo.中国姓(姓)
values('')
insert dbo.中国姓(姓)
values('蒋')
insert dbo.中国姓(姓)
values('沈')
insert dbo.中国姓(姓)
values('韩')
insert dbo.中国姓(姓)
values('杨')
insert dbo.中国姓(姓)
values('朱')
insert dbo.中国姓(姓)
values('秦')
insert dbo.中国姓(姓)
values('尤')
insert dbo.中国姓(姓)
values('许')
insert dbo.中国姓(姓)
values('何')
insert dbo.中国姓(姓)
values('吕')
insert dbo.中国姓(姓)
values('施')
insert dbo.中国姓(姓)
values('张')
insert dbo.中国姓(姓)
values('')
insert dbo.中国姓(姓)
values('孔')
insert dbo.中国姓(姓)
values('曹')
insert dbo.中国姓(姓)
values('严')
insert dbo.中国姓(姓)
values('华')
insert dbo.中国姓(姓)
values('金')
insert dbo.中国姓(姓)
values('魏')
insert dbo.中国姓(姓)
values('陶')
insert dbo.中国姓(姓)
values('姜')
insert dbo.中国姓(姓)
values('戚')
insert dbo.中国姓(姓)
values('谢')
insert dbo.中国姓(姓)
values('邹')
insert dbo.中国姓(姓)
values('喻')
insert dbo.中国姓(姓)
values('柏')
insert dbo.中国姓(姓)
values('水')
insert dbo.中国姓(姓)
values('窦')
insert dbo.中国姓(姓)
values('章')
insert dbo.中国姓(姓)
values('云')
insert dbo.中国姓(姓)
values('苏')
insert dbo.中国姓(姓)
values('潘')
insert dbo.中国姓(姓)
values('葛')
insert dbo.中国姓(姓)
values('奚')
insert dbo.中国姓(姓)
values('范')
insert dbo.中国姓(姓)
values('彭')
insert dbo.中国姓(姓)
values('郎')
insert dbo.中国姓(姓)
values('鲁')
insert dbo.中国姓(姓)
values('韦')
insert dbo.中国姓(姓)
values('昌')
insert dbo.中国姓(姓)
values('马')
insert dbo.中国姓(姓)
values('苗')
insert dbo.中国姓(姓)
values('凤')
insert dbo.中国姓(姓)
values('花')
insert dbo.中国姓(姓)
values('方')
insert dbo.中国姓(姓)
values('俞')
insert dbo.中国姓(姓)
values('任')
insert dbo.中国姓(姓)
values('袁')
insert dbo.中国姓(姓)
values('柳')
insert dbo.中国姓(姓)
values('酆')
insert dbo.中国姓(姓)
values('鲍')
insert dbo.中国姓(姓)
values('史')
insert dbo.中国姓(姓)
values('唐')
insert dbo.中国姓(姓)
values('费')
insert dbo.中国姓(姓)
values('廉')
insert dbo.中国姓(姓)
values('岑')
insert dbo.中国姓(姓)
values('薛')
insert dbo.中国姓(姓)
values('雷')
insert dbo.中国姓(姓)
values('贺')
insert dbo.中国姓(姓)
values('倪')
insert dbo.中国姓(姓)
values('汤')
insert dbo.中国姓(姓)
values('滕')
insert dbo.中国姓(姓)
values('殷')
insert dbo.中国姓(姓)
values('罗')
insert dbo.中国姓(姓)
values('毕')
insert dbo.中国姓(姓)
values('郝')
insert dbo.中国姓(姓)
values('邬')
insert dbo.中国姓(姓)
values('安')
insert dbo.中国姓(姓)
values('常')
insert dbo.中国姓(姓)
values('乐')
insert dbo.中国姓(姓)
values('于')
insert dbo.中国姓(姓)
values('时')
insert dbo.中国姓(姓)
values('傅')
insert dbo.中国姓(姓)
values('皮')
insert dbo.中国姓(姓)
values('卞')
insert dbo.中国姓(姓)
values('齐')
insert dbo.中国姓(姓)
values('康')
insert dbo.中国姓(姓)
values('伍')
insert dbo.中国姓(姓)
values('余')
insert dbo.中国姓(姓)
values('元')
insert dbo.中国姓(姓)
values('卜')
insert dbo.中国姓(姓)
values('顾')
insert dbo.中国姓(姓)
values('孟')
insert dbo.中国姓(姓)
values('平')
insert dbo.中国姓(姓)
values('黄')
insert dbo.中国姓(姓)
values('和')
insert dbo.中国姓(姓)
values('穆')
insert dbo.中国姓(姓)
values('萧')
insert dbo.中国姓(姓)
values('尹')
insert dbo.中国姓(姓)
values('姚')
insert dbo.中国姓(姓)
values('邵')
insert dbo.中国姓(姓)
values('湛')
insert dbo.中国姓(姓)
values('汪')
insert dbo.中国姓(姓)
values('祁')
insert dbo.中国姓(姓)
values('毛')
insert dbo.中国姓(姓)
values('禹')
insert dbo.中国姓(姓)
values('狄')
insert dbo.中国姓(姓)
values('米')
insert dbo.中国姓(姓)
values('贝')
insert dbo.中国姓(姓)
values('明')
insert dbo.中国姓(姓)
values('臧')
insert dbo.中国姓(姓)
values('计')
insert dbo.中国姓(姓)
values('伏')
insert dbo.中国姓(姓)
values('成')
insert dbo.中国姓(姓)
values('戴')
insert dbo.中国姓(姓)
values('谈')
insert dbo.中国姓(姓)
values('宋')
insert dbo.中国姓(姓)
values('茅')
insert dbo.中国姓(姓)
values('庞')
insert dbo.中国姓(姓)
values('熊')
insert dbo.中国姓(姓)
values('纪')
insert dbo.中国姓(姓)
values('舒')
insert dbo.中国姓(姓)
values('屈')
insert dbo.中国姓(姓)
values('项')
insert dbo.中国姓(姓)
values('祝')
insert dbo.中国姓(姓)
values('董')
insert dbo.中国姓(姓)
values('梁')
insert dbo.中国姓(姓)
values('杜')
insert dbo.中国姓(姓)
values('阮')
insert dbo.中国姓(姓)
values('蓝')
insert dbo.中国姓(姓)
values('闵')
insert dbo.中国姓(姓)
values('席')
insert dbo.中国姓(姓)
values('季')
insert dbo.中国姓(姓)
values('麻')
insert dbo.中国姓(姓)
values('强')
insert dbo.中国姓(姓)
values('贾')
insert dbo.中国姓(姓)
values('路')
insert dbo.中国姓(姓)
values('娄')
insert dbo.中国姓(姓)
values('危')
insert dbo.中国姓(姓)
values('江')
insert dbo.中国姓(姓)
values('童')
insert dbo.中国姓(姓)
values('颜')
insert dbo.中国姓(姓)
values('郭')
insert dbo.中国姓(姓)
values('梅')
insert dbo.中国姓(姓)
values('盛')
insert dbo.中国姓(姓)
values('林')
insert dbo.中国姓(姓)
values('刁')
insert dbo.中国姓(姓)
values('锺')
insert dbo.中国姓(姓)
values('徐')
insert dbo.中国姓(姓)
values('邱')
insert dbo.中国姓(姓)
values('骆')
insert dbo.中国姓(姓)
values('高')
insert dbo.中国姓(姓)
values('夏')
insert dbo.中国姓(姓)
values('蔡')
insert dbo.中国姓(姓)
values('田')
insert dbo.中国姓(姓)
values('樊')
insert dbo.中国姓(姓)
values('胡')
insert dbo.中国姓(姓)
values('凌')
insert dbo.中国姓(姓)
values('霍')
insert dbo.中国姓(姓)
values('虞')
insert dbo.中国姓(姓)
values('万')
insert dbo.中国姓(姓)
values('支')
insert dbo.中国姓(姓)
values('柯')
insert dbo.中国姓(姓)
values('昝')
insert dbo.中国姓(姓)
values('管')
insert dbo.中国姓(姓)
values('卢')
insert dbo.中国姓(姓)
values('莫')
insert dbo.中国姓(姓)
values('经')
insert dbo.中国姓(姓)
values('房')
insert dbo.中国姓(姓)
values('裘')
insert dbo.中国姓(姓)
values('缪')
insert dbo.中国姓(姓)
values('干')
insert dbo.中国姓(姓)
values('解')
insert dbo.中国姓(姓)
values('应')
insert dbo.中国姓(姓)
values('宗')
insert dbo.中国姓(姓)
values('丁')
insert dbo.中国姓(姓)
values('宣')
insert dbo.中国姓(姓)
values('贲')
insert dbo.中国姓(姓)
values('邓')
insert dbo.中国姓(姓)
values('郁')
insert dbo.中国姓(姓)
values('单')
insert dbo.中国姓(姓)
values('杭')
insert dbo.中国姓(姓)
values('洪')
insert dbo.中国姓(姓)
values('包')
insert dbo.中国姓(姓)
values('诸')
insert dbo.中国姓(姓)
values('左')
insert dbo.中国姓(姓)
values('石')
insert dbo.中国姓(姓)
values('崔')
insert dbo.中国姓(姓)
values('吉')
insert dbo.中国姓(姓)
values('钮')
insert dbo.中国姓(姓)
values('龚')
insert dbo.中国姓(姓)
values('程')
insert dbo.中国姓(姓)
values('嵇')
insert dbo.中国姓(姓)
values('邢')
insert dbo.中国姓(姓)
values('滑')
insert dbo.中国姓(姓)
values('裴')
insert dbo.中国姓(姓)
values('陆')
insert dbo.中国姓(姓)
values('荣')
insert dbo.中国姓(姓)
values('翁')
insert dbo.中国姓(姓)
values('荀')
insert dbo.中国姓(姓)
values('羊')
insert dbo.中国姓(姓)
values('於')
insert dbo.中国姓(姓)
values('惠')
insert dbo.中国姓(姓)
values('甄')
insert dbo.中国姓(姓)
values('麴')
insert dbo.中国姓(姓)
values('家')
insert dbo.中国姓(姓)
values('封')
insert dbo.中国姓(姓)
values('芮')
insert dbo.中国姓(姓)
values('羿')
insert dbo.中国姓(姓)
values('储')
insert dbo.中国姓(姓)
values('靳')
insert dbo.中国姓(姓)
values('汲')
insert dbo.中国姓(姓)
values('邴')
insert dbo.中国姓(姓)
values('糜')
insert dbo.中国姓(姓)
values('松')
insert dbo.中国姓(姓)
values('井')
insert dbo.中国姓(姓)
values('段')
insert dbo.中国姓(姓)
values('富')
insert dbo.中国姓(姓)
values('巫')
insert dbo.中国姓(姓)
values('乌')
insert dbo.中国姓(姓)
values('焦')
insert dbo.中国姓(姓)
values('巴')
insert dbo.中国姓(姓)
values('弓')
insert dbo.中国姓(姓)
values('牧')
insert dbo.中国姓(姓)
values('隗')
insert dbo.中国姓(姓)
values('山')
insert dbo.中国姓(姓)
values('谷')
insert dbo.中国姓(姓)
values('车')
insert dbo.中国姓(姓)
values('侯')
insert dbo.中国姓(姓)
values('宓')
insert dbo.中国姓(姓)
values('蓬')
insert dbo.中国姓(姓)
values('全')
insert dbo.中国姓(姓)
values('郗')
insert dbo.中国姓(姓)
values('班')
insert dbo.中国姓(姓)
values('仰')
insert dbo.中国姓(姓)
values('秋')
insert dbo.中国姓(姓)
values('仲')
insert dbo.中国姓(姓)
values('伊')
insert dbo.中国姓(姓)
values('宫')
insert dbo.中国姓(姓)
values('宁')
insert dbo.中国姓(姓)
values('仇')
insert dbo.中国姓(姓)
values('栾')
insert dbo.中国姓(姓)
values('暴')
insert dbo.中国姓(姓)
values('甘')
insert dbo.中国姓(姓)
values('钭')
insert dbo.中国姓(姓)
values('历')
insert dbo.中国姓(姓)
values('戎')
insert dbo.中国姓(姓)
values('祖')
insert dbo.中国姓(姓)
values('武')
insert dbo.中国姓(姓)
values('符')
insert dbo.中国姓(姓)
values('刘')
insert dbo.中国姓(姓)
values('景')
insert dbo.中国姓(姓)
values('詹')
insert dbo.中国姓(姓)
values('束')
insert dbo.中国姓(姓)
values('龙')
insert dbo.中国姓(姓)
values('叶')
insert dbo.中国姓(姓)
values('幸')
insert dbo.中国姓(姓)
values('司')
insert dbo.中国姓(姓)
values('韶')
insert dbo.中国姓(姓)
values('郜')
insert dbo.中国姓(姓)
values('黎')
insert dbo.中国姓(姓)
values('蓟')
insert dbo.中国姓(姓)
values('溥')
insert dbo.中国姓(姓)
values('印')
insert dbo.中国姓(姓)
values('宿')
insert dbo.中国姓(姓)
values('白')
insert dbo.中国姓(姓)
values('怀')
insert dbo.中国姓(姓)
values('蒲')
insert dbo.中国姓(姓)
values('邰')
insert dbo.中国姓(姓)
values('从')
insert dbo.中国姓(姓)
values('鄂')
insert dbo.中国姓(姓)
values('索')
insert dbo.中国姓(姓)
values('咸')
insert dbo.中国姓(姓)
values('籍')
insert dbo.中国姓(姓)
values('赖')
insert dbo.中国姓(姓)
values('卓')
insert dbo.中国姓(姓)
values('蔺')
insert dbo.中国姓(姓)
values('屠')
insert dbo.中国姓(姓)
values('蒙')
insert dbo.中国姓(姓)
values('池')
insert dbo.中国姓(姓)
values('乔')
insert dbo.中国姓(姓)
values('阳')
insert dbo.中国姓(姓)
values('郁')
insert dbo.中国姓(姓)
values('胥')
insert dbo.中国姓(姓)
values('能')
insert dbo.中国姓(姓)
values('苍')
insert dbo.中国姓(姓)
values('双')
insert dbo.中国姓(姓)
values('闻')
insert dbo.中国姓(姓)
values('莘')
insert dbo.中国姓(姓)
values('党')
insert dbo.中国姓(姓)
values('翟')
insert dbo.中国姓(姓)
values('谭')
insert dbo.中国姓(姓)
values('贡')
insert dbo.中国姓(姓)
values('劳')
insert dbo.中国姓(姓)
values('逄')
insert dbo.中国姓(姓)
values('姬')
insert dbo.中国姓(姓)
values('申')
insert dbo.中国姓(姓)
values('扶')
insert dbo.中国姓(姓)
values('堵')
insert dbo.中国姓(姓)
values('冉')
insert dbo.中国姓(姓)
values('宰')
insert dbo.中国姓(姓)
values('郦')
insert dbo.中国姓(姓)
values('雍')
insert dbo.中国姓(姓)
values('却')
insert dbo.中国姓(姓)
values('璩')
insert dbo.中国姓(姓)
values('桑')
insert dbo.中国姓(姓)
values('桂')
insert dbo.中国姓(姓)
values('濮')
insert dbo.中国姓(姓)
values('牛')
insert dbo.中国姓(姓)
values('寿')
insert dbo.中国姓(姓)
values('通')
insert dbo.中国姓(姓)
values('边')
insert dbo.中国姓(姓)
values('扈')
insert dbo.中国姓(姓)
values('燕')
insert dbo.中国姓(姓)
values('冀')
insert dbo.中国姓(姓)
values('僪')
insert dbo.中国姓(姓)
values('浦')
insert dbo.中国姓(姓)
values('尚')
insert dbo.中国姓(姓)
values('农')
insert dbo.中国姓(姓)
values('温')
insert dbo.中国姓(姓)
values('别')
insert dbo.中国姓(姓)
values('庄')
insert dbo.中国姓(姓)
values('晏')
insert dbo.中国姓(姓)
values('柴')
insert dbo.中国姓(姓)
values('瞿')
insert dbo.中国姓(姓)
values('阎')
insert dbo.中国姓(姓)
values('充')
insert dbo.中国姓(姓)
values('慕')
insert dbo.中国姓(姓)
values('连')
insert dbo.中国姓(姓)
values('茹')
insert dbo.中国姓(姓)
values('习')
insert dbo.中国姓(姓)
values('宦')
insert dbo.中国姓(姓)
values('艾')
insert dbo.中国姓(姓)
values('鱼')
insert dbo.中国姓(姓)
values('容')
insert dbo.中国姓(姓)
values('向')
insert dbo.中国姓(姓)
values('古')
insert dbo.中国姓(姓)
values('易')
insert dbo.中国姓(姓)
values('慎')
insert dbo.中国姓(姓)
values('戈')
insert dbo.中国姓(姓)
values('廖')
insert dbo.中国姓(姓)
values('庾')
insert dbo.中国姓(姓)
values('终')
insert dbo.中国姓(姓)
values('暨')
insert dbo.中国姓(姓)
values('居')
insert dbo.中国姓(姓)
values('衡')
insert dbo.中国姓(姓)
values('步')
insert dbo.中国姓(姓)
values('都')
insert dbo.中国姓(姓)
values('耿')
insert dbo.中国姓(姓)
values('满')
insert dbo.中国姓(姓)
values('弘')
insert dbo.中国姓(姓)
values('匡')
insert dbo.中国姓(姓)
values('国')
insert dbo.中国姓(姓)
values('文')
insert dbo.中国姓(姓)
values('寇')
insert dbo.中国姓(姓)
values('广')
insert dbo.中国姓(姓)
values('禄')
insert dbo.中国姓(姓)
values('阙')
insert dbo.中国姓(姓)
values('东')
insert dbo.中国姓(姓)
values('欧')
insert dbo.中国姓(姓)
values('殳')
insert dbo.中国姓(姓)
values('沃')
insert dbo.中国姓(姓)
values('利')
insert dbo.中国姓(姓)
values('蔚')
insert dbo.中国姓(姓)
values('越')
insert dbo.中国姓(姓)
values('夔')
insert dbo.中国姓(姓)
values('隆')
insert dbo.中国姓(姓)
values('师')
insert dbo.中国姓(姓)
values('巩')
insert dbo.中国姓(姓)
values('厍')
insert dbo.中国姓(姓)
values('聂')
insert dbo.中国姓(姓)
values('晁')
insert dbo.中国姓(姓)
values('勾')
insert dbo.中国姓(姓)
values('敖')
insert dbo.中国姓(姓)
values('融')
insert dbo.中国姓(姓)
values('冷')
insert dbo.中国姓(姓)
values('訾')
insert dbo.中国姓(姓)
values('辛')
insert dbo.中国姓(姓)
values('阚')
insert dbo.中国姓(姓)
values('那')
insert dbo.中国姓(姓)
values('简')
insert dbo.中国姓(姓)
values('饶')
insert dbo.中国姓(姓)
values('空')
insert dbo.中国姓(姓)
values('曾')
insert dbo.中国姓(姓)
values('毋')
insert dbo.中国姓(姓)
values('沙')
insert dbo.中国姓(姓)
values('乜')
insert dbo.中国姓(姓)
values('养')
insert dbo.中国姓(姓)
values('鞠')
insert dbo.中国姓(姓)
values('须')
insert dbo.中国姓(姓)
values('丰')
insert dbo.中国姓(姓)
values('巢')
insert dbo.中国姓(姓)
values('关')
insert dbo.中国姓(姓)
values('蒯')
insert dbo.中国姓(姓)
values('相')
insert dbo.中国姓(姓)
values('查')
insert dbo.中国姓(姓)
values('后')
insert dbo.中国姓(姓)
values('荆')
insert dbo.中国姓(姓)
values('红')
insert dbo.中国姓(姓)
values('游')
insert dbo.中国姓(姓)
values('竺')
insert dbo.中国姓(姓)
values('权')
insert dbo.中国姓(姓)
values('逮')
insert dbo.中国姓(姓)
values('盍')
insert dbo.中国姓(姓)
values('益')
insert dbo.中国姓(姓)
values('桓')
insert dbo.中国姓(姓)
values('公')
insert dbo.中国姓(姓)
values('万俟')
insert dbo.中国姓(姓)
values('司马')
insert dbo.中国姓(姓)
values('上官')
insert dbo.中国姓(姓)
values('欧阳')
insert dbo.中国姓(姓)
values('夏侯')
insert dbo.中国姓(姓)
values('诸葛')
insert dbo.中国姓(姓)
values('闻人')
insert dbo.中国姓(姓)
values('东方')
insert dbo.中国姓(姓)
values('赫连')
insert dbo.中国姓(姓)
values('皇甫')
insert dbo.中国姓(姓)
values('尉迟')
insert dbo.中国姓(姓)
values('公羊')
insert dbo.中国姓(姓)
values('澹台')
insert dbo.中国姓(姓)
values('公冶')
insert dbo.中国姓(姓)
values('宗政')
insert dbo.中国姓(姓)
values('濮阳')
insert dbo.中国姓(姓)
values('淳于')
insert dbo.中国姓(姓)
values('单于')
insert dbo.中国姓(姓)
values('太叔')
insert dbo.中国姓(姓)
values('申屠')
insert dbo.中国姓(姓)
values('公孙')
insert dbo.中国姓(姓)
values('仲孙')
insert dbo.中国姓(姓)
values('轩辕')
insert dbo.中国姓(姓)
values('令狐')
insert dbo.中国姓(姓)
values('钟离')
insert dbo.中国姓(姓)
values('宇文')
insert dbo.中国姓(姓)
values('长孙')
insert dbo.中国姓(姓)
values('慕容')
insert dbo.中国姓(姓)
values('司徒')
insert dbo.中国姓(姓)
values('司空')
insert dbo.中国姓(姓)
values('召')
insert dbo.中国姓(姓)
values('有')
insert dbo.中国姓(姓)
values('舜')
insert dbo.中国姓(姓)
values('叶赫那拉')
insert dbo.中国姓(姓)
values('丛')
insert dbo.中国姓(姓)
values('岳')
insert dbo.中国姓(姓)
values('寸')
insert dbo.中国姓(姓)
values('贰')
insert dbo.中国姓(姓)
values('皇')
insert dbo.中国姓(姓)
values('侨')
insert dbo.中国姓(姓)
values('彤')
insert dbo.中国姓(姓)
values('竭')
insert dbo.中国姓(姓)
values('端')
insert dbo.中国姓(姓)
values('赫')
insert dbo.中国姓(姓)
values('实')
insert dbo.中国姓(姓)
values('甫')
insert dbo.中国姓(姓)
values('集')
insert dbo.中国姓(姓)
values('象')
insert dbo.中国姓(姓)
values('翠')
insert dbo.中国姓(姓)
values('狂')
insert dbo.中国姓(姓)
values('辟')
insert dbo.中国姓(姓)
values('典')
insert dbo.中国姓(姓)
values('良')
insert dbo.中国姓(姓)
values('函')
insert dbo.中国姓(姓)
values('芒')
insert dbo.中国姓(姓)
values('苦')
insert dbo.中国姓(姓)
values('其')
insert dbo.中国姓(姓)
values('京')
insert dbo.中国姓(姓)
values('中')
insert dbo.中国姓(姓)
values('夕')
insert dbo.中国姓(姓)
values('之')
insert dbo.中国姓(姓)
values('章佳')
insert dbo.中国姓(姓)
values('那拉')
insert dbo.中国姓(姓)
values('冠')
insert dbo.中国姓(姓)
values('宾')
insert dbo.中国姓(姓)
values('香')
insert dbo.中国姓(姓)
values('果')
insert dbo.中国姓(姓)
values('依尔根觉罗')
insert dbo.中国姓(姓)
values('依尔觉罗')
insert dbo.中国姓(姓)
values('萨嘛喇')
insert dbo.中国姓(姓)
values('赫舍里')
insert dbo.中国姓(姓)
values('额尔德特')
insert dbo.中国姓(姓)
values('萨克达')
insert dbo.中国姓(姓)
values('钮祜禄')
insert dbo.中国姓(姓)
values('他塔喇')
insert dbo.中国姓(姓)
values('喜塔腊')
insert dbo.中国姓(姓)
values('讷殷富察')
insert dbo.中国姓(姓)
values('叶赫那兰')
insert dbo.中国姓(姓)
values('库雅喇')
insert dbo.中国姓(姓)
values('瓜尔佳')
insert dbo.中国姓(姓)
values('舒穆禄')
insert dbo.中国姓(姓)
values('爱新觉罗')
insert dbo.中国姓(姓)
values('索绰络')
insert dbo.中国姓(姓)
values('纳喇')
insert dbo.中国姓(姓)
values('乌雅')
insert dbo.中国姓(姓)
values('范姜')
insert dbo.中国姓(姓)
values('碧鲁')
insert dbo.中国姓(姓)
values('张廖')
insert dbo.中国姓(姓)
values('张简')
insert dbo.中国姓(姓)
values('图门')
insert dbo.中国姓(姓)
values('太史')
insert dbo.中国姓(姓)
values('公叔')
insert dbo.中国姓(姓)
values('乌孙')
insert dbo.中国姓(姓)
values('完颜')
insert dbo.中国姓(姓)
values('马佳')
insert dbo.中国姓(姓)
values('佟佳')
insert dbo.中国姓(姓)
values('富察')
insert dbo.中国姓(姓)
values('费莫')
insert dbo.中国姓(姓)
values('蹇')
insert dbo.中国姓(姓)
values('称')
insert dbo.中国姓(姓)
values('诺')
insert dbo.中国姓(姓)
values('来')
insert dbo.中国姓(姓)
values('多')
insert dbo.中国姓(姓)
values('繁')
insert dbo.中国姓(姓)
values('戊')
insert dbo.中国姓(姓)
values('朴')
insert dbo.中国姓(姓)
values('回')
insert dbo.中国姓(姓)
values('毓')
insert dbo.中国姓(姓)
values('税')
insert dbo.中国姓(姓)
values('荤')
insert dbo.中国姓(姓)
values('靖')
insert dbo.中国姓(姓)
values('绪')
insert dbo.中国姓(姓)
values('愈')
insert dbo.中国姓(姓)
values('硕')
insert dbo.中国姓(姓)
values('牢')
insert dbo.中国姓(姓)
values('买')
insert dbo.中国姓(姓)
values('但')
insert dbo.中国姓(姓)
values('巧')
insert dbo.中国姓(姓)
values('枚')
insert dbo.中国姓(姓)
values('撒')
insert dbo.中国姓(姓)
values('泰')
insert dbo.中国姓(姓)
values('秘')
insert dbo.中国姓(姓)
values('亥')
insert dbo.中国姓(姓)
values('绍')
insert dbo.中国姓(姓)
values('以')
insert dbo.中国姓(姓)
values('壬')
insert dbo.中国姓(姓)
values('森')
insert dbo.中国姓(姓)
values('斋')
insert dbo.中国姓(姓)
values('释')
insert dbo.中国姓(姓)
values('奕')
insert dbo.中国姓(姓)
values('姒')
insert dbo.中国姓(姓)
values('朋')
insert dbo.中国姓(姓)
values('求')
insert dbo.中国姓(姓)
values('羽')
insert dbo.中国姓(姓)
values('用')
insert dbo.中国姓(姓)
values('占')
insert dbo.中国姓(姓)
values('真')
insert dbo.中国姓(姓)
values('穰')
insert dbo.中国姓(姓)
values('翦')
insert dbo.中国姓(姓)
values('闾')
insert dbo.中国姓(姓)
values('漆')
insert dbo.中国姓(姓)
values('贵')
insert dbo.中国姓(姓)
values('代')
insert dbo.中国姓(姓)
values('贯')
insert dbo.中国姓(姓)
values('旁')
insert dbo.中国姓(姓)
values('崇')
insert dbo.中国姓(姓)
values('栋')
insert dbo.中国姓(姓)
values('告')
insert dbo.中国姓(姓)
values('休')
insert dbo.中国姓(姓)
values('褒')
insert dbo.中国姓(姓)
values('谏')
insert dbo.中国姓(姓)
values('锐')
insert dbo.中国姓(姓)
values('皋')
insert dbo.中国姓(姓)
values('闳')
insert dbo.中国姓(姓)
values('在')
insert dbo.中国姓(姓)
values('歧')
insert dbo.中国姓(姓)
values('禾')
insert dbo.中国姓(姓)
values('示')
insert dbo.中国姓(姓)
values('是')
insert dbo.中国姓(姓)
values('委')
insert dbo.中国姓(姓)
values('钊')
insert dbo.中国姓(姓)
values('频')
insert dbo.中国姓(姓)
values('嬴')
insert dbo.中国姓(姓)
values('呼')
insert dbo.中国姓(姓)
values('大')
insert dbo.中国姓(姓)
values('威')
insert dbo.中国姓(姓)
values('昂')
insert dbo.中国姓(姓)
values('律')
insert dbo.中国姓(姓)
values('冒')
insert dbo.中国姓(姓)
values('保')
insert dbo.中国姓(姓)
values('系')
insert dbo.中国姓(姓)
values('抄')
insert dbo.中国姓(姓)
values('定')
insert dbo.中国姓(姓)
values('化')
insert dbo.中国姓(姓)
values('莱')
insert dbo.中国姓(姓)
values('校')
insert dbo.中国姓(姓)
values('么')
insert dbo.中国姓(姓)
values('抗')
insert dbo.中国姓(姓)
values('祢')
insert dbo.中国姓(姓)
values('綦')
insert dbo.中国姓(姓)
values('悟')
insert dbo.中国姓(姓)
values('宏')
insert dbo.中国姓(姓)
values('功')
insert dbo.中国姓(姓)
values('庚')
insert dbo.中国姓(姓)
values('务')
insert dbo.中国姓(姓)
values('敏')
insert dbo.中国姓(姓)
values('捷')
insert dbo.中国姓(姓)
values('拱')
insert dbo.中国姓(姓)
values('兆')
insert dbo.中国姓(姓)
values('丑')
insert dbo.中国姓(姓)
values('丙')
insert dbo.中国姓(姓)
values('畅')
insert dbo.中国姓(姓)
values('苟')
insert dbo.中国姓(姓)
values('随')
insert dbo.中国姓(姓)
values('类')
insert dbo.中国姓(姓)
values('卯')
insert dbo.中国姓(姓)
values('俟')
insert dbo.中国姓(姓)
values('友')
insert dbo.中国姓(姓)
values('答')
insert dbo.中国姓(姓)
values('乙')
insert dbo.中国姓(姓)
values('允')
insert dbo.中国姓(姓)
values('甲')
insert dbo.中国姓(姓)
values('留')
insert dbo.中国姓(姓)
values('尾')
insert dbo.中国姓(姓)
values('佼')
insert dbo.中国姓(姓)
values('玄')
insert dbo.中国姓(姓)
values('乘')
insert dbo.中国姓(姓)
values('裔')
insert dbo.中国姓(姓)
values('延')
insert dbo.中国姓(姓)
values('植')
insert dbo.中国姓(姓)
values('环')
insert dbo.中国姓(姓)
values('矫')
insert dbo.中国姓(姓)
values('赛')
insert dbo.中国姓(姓)
values('昔')
insert dbo.中国姓(姓)
values('侍')
insert dbo.中国姓(姓)
values('度')
insert dbo.中国姓(姓)
values('旷')
insert dbo.中国姓(姓)
values('遇')
insert dbo.中国姓(姓)
values('偶')
insert dbo.中国姓(姓)
values('前')
insert dbo.中国姓(姓)
values('由')
insert dbo.中国姓(姓)
values('咎')
insert dbo.中国姓(姓)
values('塞')
insert dbo.中国姓(姓)
values('敛')
insert dbo.中国姓(姓)
values('受')
insert dbo.中国姓(姓)
values('泷')
insert dbo.中国姓(姓)
values('袭')
insert dbo.中国姓(姓)
values('衅')
insert dbo.中国姓(姓)
values('叔')
insert dbo.中国姓(姓)
values('圣')
insert dbo.中国姓(姓)
values('御')
insert dbo.中国姓(姓)
values('夫')
insert dbo.中国姓(姓)
values('仆')
insert dbo.中国姓(姓)
values('镇')
insert dbo.中国姓(姓)
values('藩')
insert dbo.中国姓(姓)
values('邸')
insert dbo.中国姓(姓)
values('府')
insert dbo.中国姓(姓)
values('掌')
insert dbo.中国姓(姓)
values('首')
insert dbo.中国姓(姓)
values('员')
insert dbo.中国姓(姓)
values('焉')
insert dbo.中国姓(姓)
values('戏')
insert dbo.中国姓(姓)
values('可')
insert dbo.中国姓(姓)
values('智')
insert dbo.中国姓(姓)
values('尔')
insert dbo.中国姓(姓)
values('凭')
insert dbo.中国姓(姓)
values('悉')
insert dbo.中国姓(姓)
values('进')
insert dbo.中国姓(姓)
values('笃')
insert dbo.中国姓(姓)
values('厚')
insert dbo.中国姓(姓)
values('仁')
insert dbo.中国姓(姓)
values('业')
insert dbo.中国姓(姓)
values('肇')
insert dbo.中国姓(姓)
values('资')
insert dbo.中国姓(姓)
values('合')
insert dbo.中国姓(姓)
values('仍')
insert dbo.中国姓(姓)
values('九')
insert dbo.中国姓(姓)
values('衷')
insert dbo.中国姓(姓)
values('哀')
insert dbo.中国姓(姓)
values('刑')
insert dbo.中国姓(姓)
values('俎')
insert dbo.中国姓(姓)
values('仵')
insert dbo.中国姓(姓)
values('圭')
insert dbo.中国姓(姓)
values('夷')
insert dbo.中国姓(姓)
values('徭')
insert dbo.中国姓(姓)
values('蛮')
insert dbo.中国姓(姓)
values('汗')
insert dbo.中国姓(姓)
values('孛')
insert dbo.中国姓(姓)
values('乾')
insert dbo.中国姓(姓)
values('帖')
insert dbo.中国姓(姓)
values('罕')
insert dbo.中国姓(姓)
values('洛')
insert dbo.中国姓(姓)
values('淦')
insert dbo.中国姓(姓)
values('洋')
insert dbo.中国姓(姓)
values('邶')
insert dbo.中国姓(姓)
values('郸')
insert dbo.中国姓(姓)
values('郯')
insert dbo.中国姓(姓)
values('邗')
insert dbo.中国姓(姓)
values('邛')
insert dbo.中国姓(姓)
values('剑')
insert dbo.中国姓(姓)
values('虢')
insert dbo.中国姓(姓)
values('隋')
insert dbo.中国姓(姓)
values('蒿')
insert dbo.中国姓(姓)
values('茆')
insert dbo.中国姓(姓)
values('菅')
insert dbo.中国姓(姓)
values('苌')
insert dbo.中国姓(姓)
values('树')
insert dbo.中国姓(姓)
values('桐')
insert dbo.中国姓(姓)
values('锁')
insert dbo.中国姓(姓)
values('钟')
insert dbo.中国姓(姓)
values('机')
insert dbo.中国姓(姓)
values('盘')
insert dbo.中国姓(姓)
values('铎')
insert dbo.中国姓(姓)
values('斛')
insert dbo.中国姓(姓)
values('玉')
insert dbo.中国姓(姓)
values('线')
insert dbo.中国姓(姓)
values('针')
insert dbo.中国姓(姓)
values('箕')
insert dbo.中国姓(姓)
values('庹')
insert dbo.中国姓(姓)
values('绳')
insert dbo.中国姓(姓)
values('磨')
insert dbo.中国姓(姓)
values('蒉')
insert dbo.中国姓(姓)
values('瓮')
insert dbo.中国姓(姓)
values('弭')
insert dbo.中国姓(姓)
values('刀')
insert dbo.中国姓(姓)
values('疏')
insert dbo.中国姓(姓)
values('牵')
insert dbo.中国姓(姓)
values('浑')
insert dbo.中国姓(姓)
values('恽')
insert dbo.中国姓(姓)
values('势')
insert dbo.中国姓(姓)
values('世')
insert dbo.中国姓(姓)
values('仝')
insert dbo.中国姓(姓)
values('同')
insert dbo.中国姓(姓)
values('蚁')
insert dbo.中国姓(姓)
values('止')
insert dbo.中国姓(姓)
values('戢')
insert dbo.中国姓(姓)
values('睢')
insert dbo.中国姓(姓)
values('冼')
insert dbo.中国姓(姓)
values('种')
insert dbo.中国姓(姓)
values('涂')
insert dbo.中国姓(姓)
values('肖')
insert dbo.中国姓(姓)
values('己')
insert dbo.中国姓(姓)
values('泣')
insert dbo.中国姓(姓)
values('潜')
insert dbo.中国姓(姓)
values('卷')
insert dbo.中国姓(姓)
values('脱')
insert dbo.中国姓(姓)
values('谬')
insert dbo.中国姓(姓)
values('蹉')
insert dbo.中国姓(姓)
values('赧')
insert dbo.中国姓(姓)
values('浮')
insert dbo.中国姓(姓)
values('顿')
insert dbo.中国姓(姓)
values('说')
insert dbo.中国姓(姓)
values('次')
insert dbo.中国姓(姓)
values('错')
insert dbo.中国姓(姓)
values('念')
insert dbo.中国姓(姓)
values('夙')
insert dbo.中国姓(姓)
values('斯')
insert dbo.中国姓(姓)
values('完')
insert dbo.中国姓(姓)
values('丹')
insert dbo.中国姓(姓)
values('表')
insert dbo.中国姓(姓)
values('聊')
insert dbo.中国姓(姓)
values('源')
insert dbo.中国姓(姓)
values('姓')
insert dbo.中国姓(姓)
values('吾')
insert dbo.中国姓(姓)
values('寻')
insert dbo.中国姓(姓)
values('展')
insert dbo.中国姓(姓)
values('出')
insert dbo.中国姓(姓)
values('不')
insert dbo.中国姓(姓)
values('户')
insert dbo.中国姓(姓)
values('闭')
insert dbo.中国姓(姓)
values('才')
insert dbo.中国姓(姓)
values('无')
insert dbo.中国姓(姓)
values('书')
insert dbo.中国姓(姓)
values('学')
insert dbo.中国姓(姓)
values('愚')
insert dbo.中国姓(姓)
values('本')
insert dbo.中国姓(姓)
values('性')
insert dbo.中国姓(姓)
values('雪')
insert dbo.中国姓(姓)
values('霜')
insert dbo.中国姓(姓)
values('烟')
insert dbo.中国姓(姓)
values('寒')
insert dbo.中国姓(姓)
values('少')
insert dbo.中国姓(姓)
values('字')
insert dbo.中国姓(姓)
values('桥')
insert dbo.中国姓(姓)
values('板')
insert dbo.中国姓(姓)
values('斐')
insert dbo.中国姓(姓)
values('独')
insert dbo.中国姓(姓)
values('千')
insert dbo.中国姓(姓)
values('诗')
insert dbo.中国姓(姓)
values('嘉')
insert dbo.中国姓(姓)
values('扬')
insert dbo.中国姓(姓)
values('善')
insert dbo.中国姓(姓)
values('揭')
insert dbo.中国姓(姓)
values('祈')
insert dbo.中国姓(姓)
values('析')
insert dbo.中国姓(姓)
values('赤')
insert dbo.中国姓(姓)
values('紫')
insert dbo.中国姓(姓)
values('青')
insert dbo.中国姓(姓)
values('柔')
insert dbo.中国姓(姓)
values('刚')
insert dbo.中国姓(姓)
values('奇')
insert dbo.中国姓(姓)
values('拜')
insert dbo.中国姓(姓)
values('佛')
insert dbo.中国姓(姓)
values('陀')
insert dbo.中国姓(姓)
values('弥')
insert dbo.中国姓(姓)
values('阿')
insert dbo.中国姓(姓)
values('素')
insert dbo.中国姓(姓)
values('长')
insert dbo.中国姓(姓)
values('僧')
insert dbo.中国姓(姓)
values('隐')
insert dbo.中国姓(姓)
values('仙')
insert dbo.中国姓(姓)
values('隽')
insert dbo.中国姓(姓)
values('宇')
insert dbo.中国姓(姓)
values('祭')
insert dbo.中国姓(姓)
values('酒')
insert dbo.中国姓(姓)
values('淡')
insert dbo.中国姓(姓)
values('塔')
insert dbo.中国姓(姓)
values('琦')
insert dbo.中国姓(姓)
values('闪')
insert dbo.中国姓(姓)
values('始')
insert dbo.中国姓(姓)
values('星')
insert dbo.中国姓(姓)
values('南')
insert dbo.中国姓(姓)
values('天')
insert dbo.中国姓(姓)
values('接')
insert dbo.中国姓(姓)
values('波')
insert dbo.中国姓(姓)
values('碧')
insert dbo.中国姓(姓)
values('速')
insert dbo.中国姓(姓)
values('禚')
insert dbo.中国姓(姓)
values('腾')
insert dbo.中国姓(姓)
values('潮')
insert dbo.中国姓(姓)
values('镜')
insert dbo.中国姓(姓)
values('似')
insert dbo.中国姓(姓)
values('澄')
insert dbo.中国姓(姓)
values('潭')
insert dbo.中国姓(姓)
values('謇')
insert dbo.中国姓(姓)
values('纵')
insert dbo.中国姓(姓)
values('渠')
insert dbo.中国姓(姓)
values('奈')
insert dbo.中国姓(姓)
values('风')
insert dbo.中国姓(姓)
values('春')
insert dbo.中国姓(姓)
values('濯')
insert dbo.中国姓(姓)
values('沐')
insert dbo.中国姓(姓)
values('茂')
insert dbo.中国姓(姓)
values('英')
insert dbo.中国姓(姓)
values('兰')
insert dbo.中国姓(姓)
values('檀')
insert dbo.中国姓(姓)
values('藤')
insert dbo.中国姓(姓)
values('枝')
insert dbo.中国姓(姓)
values('检')
insert dbo.中国姓(姓)
values('生')
insert dbo.中国姓(姓)
values('折')
insert dbo.中国姓(姓)
values('登')
insert dbo.中国姓(姓)
values('驹')
insert dbo.中国姓(姓)
values('骑')
insert dbo.中国姓(姓)
values('貊')
insert dbo.中国姓(姓)
values('虎')
insert dbo.中国姓(姓)
values('肥')
insert dbo.中国姓(姓)
values('鹿')
insert dbo.中国姓(姓)
values('雀')
insert dbo.中国姓(姓)
values('野')
insert dbo.中国姓(姓)
values('禽')
insert dbo.中国姓(姓)
values('飞')
insert dbo.中国姓(姓)
values('节')
insert dbo.中国姓(姓)
values('宜')
insert dbo.中国姓(姓)
values('鲜')
insert dbo.中国姓(姓)
values('粟')
insert dbo.中国姓(姓)
values('栗')
insert dbo.中国姓(姓)
values('豆')
insert dbo.中国姓(姓)
values('帛')
insert dbo.中国姓(姓)
values('官')
insert dbo.中国姓(姓)
values('布')
insert dbo.中国姓(姓)
values('衣')
insert dbo.中国姓(姓)
values('藏')
insert dbo.中国姓(姓)
values('宝')
insert dbo.中国姓(姓)
values('钞')
insert dbo.中国姓(姓)
values('银')
insert dbo.中国姓(姓)
values('门')
insert dbo.中国姓(姓)
values('盈')
insert dbo.中国姓(姓)
values('庆')
insert dbo.中国姓(姓)
values('喜')
insert dbo.中国姓(姓)
values('及')
insert dbo.中国姓(姓)
values('普')
insert dbo.中国姓(姓)
values('建')
insert dbo.中国姓(姓)
values('营')
insert dbo.中国姓(姓)
values('巨')
insert dbo.中国姓(姓)
values('望')
insert dbo.中国姓(姓)
values('希')
insert dbo.中国姓(姓)
values('道')
insert dbo.中国姓(姓)
values('载')
insert dbo.中国姓(姓)
values('声')
insert dbo.中国姓(姓)
values('漫')
insert dbo.中国姓(姓)
values('犁')
insert dbo.中国姓(姓)
values('力')
insert dbo.中国姓(姓)
values('贸')
insert dbo.中国姓(姓)
values('勤')
insert dbo.中国姓(姓)
values('革')
insert dbo.中国姓(姓)
values('改')
insert dbo.中国姓(姓)
values('兴')
insert dbo.中国姓(姓)
values('亓')
insert dbo.中国姓(姓)
values('睦')
insert dbo.中国姓(姓)
values('修')
insert dbo.中国姓(姓)
values('信')
insert dbo.中国姓(姓)
values('闽')
insert dbo.中国姓(姓)
values('北')
insert dbo.中国姓(姓)
values('守')
insert dbo.中国姓(姓)
values('坚')
insert dbo.中国姓(姓)
values('勇')
insert dbo.中国姓(姓)
values('汉')
insert dbo.中国姓(姓)
values('练')
insert dbo.中国姓(姓)
values('尉')
insert dbo.中国姓(姓)
values('士')
insert dbo.中国姓(姓)
values('旅')
insert dbo.中国姓(姓)
values('五')
insert dbo.中国姓(姓)
values('令')
insert dbo.中国姓(姓)
values('将')
insert dbo.中国姓(姓)
values('旗')
insert dbo.中国姓(姓)
values('军')
insert dbo.中国姓(姓)
values('行')
insert dbo.中国姓(姓)
values('奉')
insert dbo.中国姓(姓)
values('敬')
insert dbo.中国姓(姓)
values('恭')
insert dbo.中国姓(姓)
values('仪')
insert dbo.中国姓(姓)
values('母')
insert dbo.中国姓(姓)
values('堂')
insert dbo.中国姓(姓)
values('丘')
insert dbo.中国姓(姓)
values('义')
insert dbo.中国姓(姓)
values('礼')
insert dbo.中国姓(姓)
values('慈')
insert dbo.中国姓(姓)
values('孝')
insert dbo.中国姓(姓)
values('理')
insert dbo.中国姓(姓)
values('伦')
insert dbo.中国姓(姓)
values('卿')
insert dbo.中国姓(姓)
values('问')
insert dbo.中国姓(姓)
values('永')
insert dbo.中国姓(姓)
values('辉')
insert dbo.中国姓(姓)
values('位')
insert dbo.中国姓(姓)
values('让')
insert dbo.中国姓(姓)
values('尧')
insert dbo.中国姓(姓)
values('依')
insert dbo.中国姓(姓)
values('犹')
insert dbo.中国姓(姓)
values('介')
insert dbo.中国姓(姓)
values('承')
insert dbo.中国姓(姓)
values('市')
insert dbo.中国姓(姓)
values('所')
insert dbo.中国姓(姓)
values('苑')
insert dbo.中国姓(姓)
values('杞')
insert dbo.中国姓(姓)
values('剧')
insert dbo.中国姓(姓)
values('第')
insert dbo.中国姓(姓)
values('零')
insert dbo.中国姓(姓)
values('谌')
insert dbo.中国姓(姓)
values('招')
insert dbo.中国姓(姓)
values('续')
insert dbo.中国姓(姓)
values('达')
insert dbo.中国姓(姓)
values('忻')
insert dbo.中国姓(姓)
values('六')
insert dbo.中国姓(姓)
values('鄞')
insert dbo.中国姓(姓)
values('战')
insert dbo.中国姓(姓)
values('迟')
insert dbo.中国姓(姓)
values('候')
insert dbo.中国姓(姓)
values('宛')
insert dbo.中国姓(姓)
values('励')
insert dbo.中国姓(姓)
values('粘')
insert dbo.中国姓(姓)
values('萨')
insert dbo.中国姓(姓)
values('邝')
insert dbo.中国姓(姓)
values('覃')
insert dbo.中国姓(姓)
values('辜')
insert dbo.中国姓(姓)
values('初')
insert dbo.中国姓(姓)
values('楼')
insert dbo.中国姓(姓)
values('城')
insert dbo.中国姓(姓)
values('区')
insert dbo.中国姓(姓)
values('局')
insert dbo.中国姓(姓)
values('台')
insert dbo.中国姓(姓)
values('原')
insert dbo.中国姓(姓)
values('考')
insert dbo.中国姓(姓)
values('妫')
insert dbo.中国姓(姓)
values('纳')
insert dbo.中国姓(姓)
values('泉')
insert dbo.中国姓(姓)
values('老')
insert dbo.中国姓(姓)
values('清')
insert dbo.中国姓(姓)
values('德')
insert dbo.中国姓(姓)
values('卑')
insert dbo.中国姓(姓)
values('过')
insert dbo.中国姓(姓)
values('麦')
insert dbo.中国姓(姓)
values('曲')
insert dbo.中国姓(姓)
values('竹')
insert dbo.中国姓(姓)
values('百')
insert dbo.中国姓(姓)
values('福')
insert dbo.中国姓(姓)
values('言')
insert dbo.中国姓(姓)
values('第五')
insert dbo.中国姓(姓)
values('佟')
insert dbo.中国姓(姓)
values('爱')
insert dbo.中国姓(姓)
values('年')
insert dbo.中国姓(姓)
values('笪')
insert dbo.中国姓(姓)
values('谯')
insert dbo.中国姓(姓)
values('哈')
insert dbo.中国姓(姓)
values('墨')
insert dbo.中国姓(姓)
values('南宫')
insert dbo.中国姓(姓)
values('赏')
insert dbo.中国姓(姓)
values('伯')
insert dbo.中国姓(姓)
values('佴')
insert dbo.中国姓(姓)
values('佘')
insert dbo.中国姓(姓)
values('牟')
insert dbo.中国姓(姓)
values('商')
insert dbo.中国姓(姓)
values('西门')
insert dbo.中国姓(姓)
values('东门')
insert dbo.中国姓(姓)
values('左丘')
insert dbo.中国姓(姓)
values('梁丘')
insert dbo.中国姓(姓)
values('琴')
insert dbo.中国姓(姓)
values('后')
insert dbo.中国姓(姓)
values('况')
insert dbo.中国姓(姓)
values('亢')
insert dbo.中国姓(姓)
values('缑')
insert dbo.中国姓(姓)
values('帅')
insert dbo.中国姓(姓)
values('微生')
insert dbo.中国姓(姓)
values('羊舌')
insert dbo.中国姓(姓)
values('海')
insert dbo.中国姓(姓)
values('归')
insert dbo.中国姓(姓)
values('呼延')
insert dbo.中国姓(姓)
values('南门')
insert dbo.中国姓(姓)
values('东郭')
insert dbo.中国姓(姓)
values('百里')
insert dbo.中国姓(姓)
values('钦')
insert dbo.中国姓(姓)
values('鄢')
insert dbo.中国姓(姓)
values('汝')
insert dbo.中国姓(姓)
values('法')
insert dbo.中国姓(姓)
values('闫')
insert dbo.中国姓(姓)
values('楚')
insert dbo.中国姓(姓)
values('晋')
insert dbo.中国姓(姓)
values('谷梁')
insert dbo.中国姓(姓)
values('宰父')
insert dbo.中国姓(姓)
values('夹谷')
insert dbo.中国姓(姓)
values('拓跋')
insert dbo.中国姓(姓)
values('壤驷')
insert dbo.中国姓(姓)
values('乐正')
insert dbo.中国姓(姓)
values('漆雕')
insert dbo.中国姓(姓)
values('公西')
insert dbo.中国姓(姓)
values('巫马')
insert dbo.中国姓(姓)
values('端木')
insert dbo.中国姓(姓)
values('颛孙')
insert dbo.中国姓(姓)
values('子车')
insert dbo.中国姓(姓)
values('督')
insert dbo.中国姓(姓)
values('仉')
insert dbo.中国姓(姓)
values('司寇')
insert dbo.中国姓(姓)
values('亓官')
insert dbo.中国姓(姓)
values('鲜于')
insert dbo.中国姓(姓)
values('锺离')
insert dbo.中国姓(姓)
values('盖')
insert dbo.中国姓(姓)
values('逯')
insert dbo.中国姓(姓)
values('库')
insert dbo.中国姓(姓)
values('郏')
insert dbo.中国姓(姓)
values('逢')
insert dbo.中国姓(姓)
values('阴')
insert dbo.中国姓(姓)
values('薄')
insert dbo.中国姓(姓)
values('厉')
insert dbo.中国姓(姓)
values('稽')
insert dbo.中国姓(姓)
values('闾丘')
insert dbo.中国姓(姓)
values('公良')
insert dbo.中国姓(姓)
values('段干')
insert dbo.中国姓(姓)
values('开')
insert dbo.中国姓(姓)
values('光')
insert dbo.中国姓(姓)
values('操')
insert dbo.中国姓(姓)
values('瑞')
insert dbo.中国姓(姓)
values('眭')
insert dbo.中国姓(姓)
values('泥')
insert dbo.中国姓(姓)
values('运')
insert dbo.中国姓(姓)
values('摩')
insert dbo.中国姓(姓)
values('伟')
insert dbo.中国姓(姓)
values('铁')
insert dbo.中国姓(姓)
values('迮')